import type { Chat } from "@/lib/store/slices/chat-slice"

export const mockChats: Chat[] = [
  {
    id: "1",
    participantId: "user1",
    participantName: "Alice Johnson",
    participantUsername: "alice",
    unreadCount: 2,
    isOnline: true,
    isViewing: true,
    messages: [
      {
        id: "m1",
        content: "Hey, how are you?",
        senderId: "user1",
        receiverId: "me",
        timestamp: "10:30 AM",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m2",
        content: "I'm good, thanks! How about you?",
        senderId: "me",
        receiverId: "user1",
        timestamp: "10:31 AM",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m3",
        content: "Did you get the documents I sent?",
        senderId: "user1",
        receiverId: "me",
        timestamp: "10:32 AM",
        isEncrypted: true,
        isRead: false,
      },
      {
        id: "m4",
        content: "Yes, reviewing them now!",
        senderId: "me",
        receiverId: "user1",
        timestamp: "10:33 AM",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m5",
        content: "Great, let me know your thoughts.",
        senderId: "user1",
        receiverId: "me",
        timestamp: "10:34 AM",
        isEncrypted: true,
        isRead: false,
      },
    ],
  },
  {
    id: "2",
    participantId: "user2",
    participantName: "Bob Smith",
    participantUsername: "bobsmith",
    unreadCount: 0,
    isOnline: true,
    isViewing: false,
    messages: [
      {
        id: "m6",
        content: "Meeting at 3pm tomorrow?",
        senderId: "user2",
        receiverId: "me",
        timestamp: "9:15 AM",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m7",
        content: "Sure, works for me!",
        senderId: "me",
        receiverId: "user2",
        timestamp: "9:20 AM",
        isEncrypted: true,
        isRead: true,
      },
    ],
  },
  {
    id: "3",
    participantId: "user3",
    participantName: "Carol Davis",
    participantUsername: "carol_d",
    unreadCount: 5,
    isOnline: false,
    isViewing: false,
    messages: [
      {
        id: "m8",
        content: "Check out this encrypted file",
        senderId: "user3",
        receiverId: "me",
        timestamp: "Yesterday",
        isEncrypted: true,
        isRead: false,
      },
    ],
  },
]
