import type { Chat } from "@/lib/store/slices/chat-slice"

export const mockChats: Chat[] = [
  {
    id: "1",
    participantId: "user1",
    participantName: "Alice Johnson",
    participantUsername: "alice",
    unreadCount: 2,
    isOnline: true,
    isViewing: true,
    isGroup: false,
    messages: [
      {
        id: "m1",
        content: "Hey, how are you?",
        senderId: "user1",
        receiverId: "me",
        timestamp: "10:30 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m2",
        content: "I'm good, thanks! How about you?",
        senderId: "me",
        receiverId: "user1",
        timestamp: "10:31 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m3",
        content: "Did you get the documents I sent?",
        senderId: "user1",
        receiverId: "me",
        timestamp: "10:32 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: false,
      },
      {
        id: "m4",
        content: "Yes, reviewing them now!",
        senderId: "me",
        receiverId: "user1",
        timestamp: "10:33 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m5",
        content: "Great, let me know your thoughts.",
        senderId: "user1",
        receiverId: "me",
        timestamp: "10:34 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: false,
      },
    ],
  },
  {
    id: "2",
    participantId: "user2",
    participantName: "Bob Smith",
    participantUsername: "bobsmith",
    unreadCount: 0,
    isOnline: true,
    isViewing: false,
    isGroup: false,
    messages: [
      {
        id: "m6",
        content: "Meeting at 3pm tomorrow?",
        senderId: "user2",
        receiverId: "me",
        timestamp: "9:15 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m7",
        content: "Sure, works for me!",
        senderId: "me",
        receiverId: "user2",
        timestamp: "9:20 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: true,
      },
    ],
  },
  {
    id: "3",
    participantId: "user3",
    participantName: "Carol Davis",
    participantUsername: "carol_d",
    unreadCount: 5,
    isOnline: false,
    isViewing: false,
    isGroup: false,
    messages: [
      {
        id: "m8",
        content: "Check out this encrypted file",
        senderId: "user3",
        receiverId: "me",
        timestamp: "3:12 PM",
        dayLabel: "Yesterday",
        isEncrypted: true,
        isRead: false,
      },
    ],
  },
  {
    id: "4",
    participantId: "group1",
    participantName: "Design Guild",
    participantUsername: "design-guild",
    unreadCount: 3,
    isOnline: true,
    isViewing: false,
    isGroup: true,
    messages: [
      {
        id: "m9",
        content: "Welcome to the guild!",
        senderId: "user7",
        senderName: "Riley Chen",
        senderAvatar: "/placeholder.svg",
        receiverId: "me",
        timestamp: "8:01 PM",
        dayLabel: "Yesterday",
        isEncrypted: true,
        isRead: false,
      },
      {
        id: "m11",
        content: "We are reviewing the new brand deck tomorrow.",
        senderId: "user8",
        senderName: "Nora Miles",
        senderAvatar: "/placeholder.svg",
        receiverId: "me",
        timestamp: "8:05 PM",
        dayLabel: "Yesterday",
        isEncrypted: true,
        isRead: false,
      },
      {
        id: "m12",
        content: "I can lead the typography section.",
        senderId: "me",
        senderName: "You",
        senderAvatar: "/placeholder.svg",
        receiverId: "group1",
        timestamp: "8:07 PM",
        dayLabel: "Yesterday",
        isEncrypted: true,
        isRead: true,
      },
      {
        id: "m13",
        content: "Great. Please drop any references in the shared folder.",
        senderId: "user7",
        senderName: "Riley Chen",
        senderAvatar: "/placeholder.svg",
        receiverId: "me",
        timestamp: "9:10 AM",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: false,
      },
    ],
  },
  {
    id: "5",
    participantId: "user4",
    participantName: "Evan Brooks",
    participantUsername: "evanb",
    unreadCount: 1,
    isOnline: false,
    isViewing: false,
    isRequest: true,
    isGroup: false,
    messages: [
      {
        id: "m10",
        content: "Hey! Can we connect?",
        senderId: "user4",
        receiverId: "me",
        timestamp: "Today",
        dayLabel: "Today",
        isEncrypted: true,
        isRead: false,
      },
    ],
  },
]
